image: node:7

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - make build

deploy:
  stage: deploy
  script:
    - apt-get update
    - apt-get install s3cmd -y
    - make deploy
  environment:
    name: staging
    url: https://styleguide.sos.exo.io/index.html
  only:
    - master
