version: "3.4"
services:
  republik-backend:
    build:
      context: ./servers/republik
    image: republik-backend:latest
    links:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres@postgres:5432/republik
      - REDIS_URL=redis:6379
      - PUBLIC_URL=http://localhost:8080
      - FRONTEND_BASE_URL
      - SESSION_SECRET
      - CORS_ALLOWLIST_URL
      - SEND_MAILS
      - MANDRILL_API_KEY
      - DEFAULT_MAIL_FROM_NAME
      - DEFAULT_MAIL_FROM_ADDRESS
      - DISPLAY_AUTHOR_SECRET
      - EXO_KEY
      - EXO_SECRET
      - S3BUCKET
      - ASSETS_BASE_URL
      - KEYCDN_API_KEY
      - KEYCDN_ZONE_ID
      - KEYCDN_ZONE_URL
      - CHROMIUM_LAMBDA_URL
    ports:
        - 8080:3020
