name: Bug Report 🐛
description: Create a bug report if you encounter a problem in the application.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Tell us how and when the bug occured. If it's a visaul bug, please include a screenshot.
      placeholder: "I was writting a comment under an article…"
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behaviour
      description: What was the expected behavior?
      placeholder: "I would expect the comment to…"
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: What steps are necessary to reproduce the bug?
      placeholder: "I visited republik.ch/foo/bar and…"
  - type: dropdown
    id: platform
    attributes:
      label: Environment
      description: Where did you experience the bug?
      options:
        - App (iOS/iPadOS)
        - App (Android)
        - Safari
        - Chrome
        - Firefox
        - Other (please specify in version field below)
    validations:
      required: true
  - type: input
    id: platform-version
    attributes:
      label: Version
      description: Version of the browser or the Republik app where the bug occured.