[http]
  [http.routers]
    [http.routers.api]
      entryPoints = ["web"]
      rule = "Host(`api.republik.test`)"
      service = "api"
    [http.routers.publikator-api]
      entryPoints = ["web"]
      rule = "Host(`api.publikator.republik.test`)"
      service = "publikator-api"
    [http.routers.assets-api]
      entryPoints = ["web"]
      rule = "Host(`assets.republik.test`)"
      service = "assets-api"
    [http.routers.frontend]
      entryPoints = ["web"]
      rule = "Host(`republik.test`)"
      service = "frontend"
    [http.routers.admin-frontend]
      entryPoints = ["web"]
      rule = "Host(`admin.republik.test`)"
      service = "admin-frontend"
    [http.routers.publikator-frontend]
      entryPoints = ["web"]
      rule = "Host(`publikator.republik.test`)"
      service = "publikator-frontend"
    [http.routers.styleguide]
      entryPoints = ["web"]
      rule = "Host(`styleguide.republik.test`)"
      service = "styleguide"
    [http.routers.misc]
      entryPoints = ["web"]
      rule = "Host(`misc.republik.test`)"
      service = "misc"

  [http.services]
    [[http.services.api.loadBalancer.servers]]
      url = "http://localhost:5010"
    [[http.services.publikator-api.loadBalancer.servers]]
      url = "http://localhost:5010"
    [[http.services.assets-api.loadBalancer.servers]]
      url = "http://localhost:5020"
    [[http.services.frontend.loadBalancer.servers]]
      url = "http://localhost:3010"
    [[http.services.admin-frontend.loadBalancer.servers]]
      url = "http://localhost:3006"
    [[http.services.publikator-frontend.loadBalancer.servers]]
      url = "http://localhost:3005"
    [[http.services.styleguide.loadBalancer.servers]]
      url = "http://localhost:3003"
    [[http.services.misc.loadBalancer.servers]]
      url = "http://localhost:3000"
